---------------------------------------------------------------------
-- Banner Production Profiles
---------------------------------------------------------------------

alter profile DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		UNLIMITED
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			.01
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		-1
		PASSWORD_VERIFY_FUNCTION	NULL;


alter profile ND_APP_LOCK_BANNER limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_APP_LOCK_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_APP_OPEN_BANNER limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_APP_OPEN_DATA_INTEGRATOR limit
		COMPOSITE_LIMIT				DEFAULT
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				DEFAULT
		CPU_PER_SESSION				DEFAULT
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		DEFAULT
		LOGICAL_READS_PER_SESSION	DEFAULT
		PRIVATE_SGA					DEFAULT
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		DEFAULT
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			14
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			DEFAULT
		PASSWORD_REUSE_MAX			DEFAULT
		PASSWORD_REUSE_TIME			DEFAULT
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	NULL;


alter profile ND_APP_OPEN_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_APP_OPEN_SSB limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_LNK_OPEN_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_OWN_LOCK_BANNER limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_OWN_LOCK_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_OWN_OPEN_BANNER limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_OWN_OPEN_DATA_INTEGRATOR limit
		COMPOSITE_LIMIT				DEFAULT
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				DEFAULT
		CPU_PER_SESSION				DEFAULT
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		DEFAULT
		LOGICAL_READS_PER_SESSION	DEFAULT
		PRIVATE_SGA					DEFAULT
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		DEFAULT
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			14
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			DEFAULT
		PASSWORD_REUSE_MAX			DEFAULT
		PASSWORD_REUSE_TIME			DEFAULT
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	NULL;


alter profile ND_OWN_OPEN_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_SYS_LOCK_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_SYS_LOCK_ORACLE limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_SYS_OPEN_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_SYS_OPEN_OPERATIONS limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_SYS_OPEN_ORACLE limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_SYS_OPEN_PIPES limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_LOCK_BUYND limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_LOCK_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_LOCK_EFFORT_CERT limit
		COMPOSITE_LIMIT				DEFAULT
		CONNECT_TIME				DEFAULT
		CPU_PER_CALL				DEFAULT
		CPU_PER_SESSION				DEFAULT
		IDLE_TIME					DEFAULT
		LOGICAL_READS_PER_CALL		DEFAULT
		LOGICAL_READS_PER_SESSION	DEFAULT
		PRIVATE_SGA					DEFAULT
		SESSIONS_PER_USER			1
		FAILED_LOGIN_ATTEMPTS		DEFAULT
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			DEFAULT
		PASSWORD_LIFE_TIME			DEFAULT
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			DEFAULT
		PASSWORD_REUSE_TIME			DEFAULT
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_LOCK_PEOPLE_EZ limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_OPEN_BOSSCARS limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_OPEN_DBA limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_OPEN_DEFAULT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_OPEN_DEVELOPER limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_OPEN_EPRINT limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_OPEN_INBUSER limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_OPEN_POWERUSER limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			DEFAULT
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ND_USR_OPEN_QA limit
		COMPOSITE_LIMIT				UNLIMITED
		CONNECT_TIME				UNLIMITED
		CPU_PER_CALL				UNLIMITED
		CPU_PER_SESSION				UNLIMITED
		IDLE_TIME					UNLIMITED
		LOGICAL_READS_PER_CALL		UNLIMITED
		LOGICAL_READS_PER_SESSION	UNLIMITED
		PRIVATE_SGA					UNLIMITED
		SESSIONS_PER_USER			UNLIMITED
		FAILED_LOGIN_ATTEMPTS		10
		INACTIVE_ACCOUNT_TIME		DEFAULT
		PASSWORD_GRACE_TIME			UNLIMITED
		PASSWORD_LIFE_TIME			UNLIMITED
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			UNLIMITED
		PASSWORD_REUSE_TIME			UNLIMITED
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	DEFAULT;


alter profile ORA_STIG_PROFILE limit
		COMPOSITE_LIMIT				DEFAULT
		CONNECT_TIME				DEFAULT
		CPU_PER_CALL				DEFAULT
		CPU_PER_SESSION				DEFAULT
		IDLE_TIME					15
		LOGICAL_READS_PER_CALL		DEFAULT
		LOGICAL_READS_PER_SESSION	DEFAULT
		PRIVATE_SGA					DEFAULT
		SESSIONS_PER_USER			DEFAULT
		FAILED_LOGIN_ATTEMPTS		3
		INACTIVE_ACCOUNT_TIME		35
		PASSWORD_GRACE_TIME			5
		PASSWORD_LIFE_TIME			60
		PASSWORD_LOCK_TIME			UNLIMITED
		PASSWORD_REUSE_MAX			10
		PASSWORD_REUSE_TIME			365
		PASSWORD_ROLLOVER_TIME		DEFAULT
		PASSWORD_VERIFY_FUNCTION	ORA12C_STIG_VERIFY_FUNCTION;

